[workspace]
members = ["bop", "bop-cli"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stevepryde/bop-lang"
homepage = "https://github.com/stevepryde/bop-lang"
authors = ["Steve Pryde"]
